### Create new user
POST localhost:8082/api/v1/user/create_user
Content-Type: application/json

{
  "firstName": "Vadim",
  "lastName": "Volkov",
  "username": "1234567869696933",
  "password": "superuser69"
}

### Find all users
GET localhost:8082/api/v1/user/get_all
Authorization: Basic YWRtaW46YWRtaW4=

### Find user by auth_id
GET localhost:8082/api/v1/user/find_by_auth_id/9999999999999999
