server:
  port: 8082

spring:
  security:
    user:
      name: admin
      password: admin
      roles: admin

  datasource:
    url: jdbc:postgresql://localhost:54321/postgres
    username: postgres
    password: postgres

  jpa:
    show-sql: true
    generate-ddl: true